# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/sim_launcher.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 547, 741))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textbox_status = QtWidgets.QTextBrowser(self.gridLayoutWidget_3)
        self.textbox_status.setObjectName("textbox_status")
        self.verticalLayout.addWidget(self.textbox_status)
        self.sim_grid = QtWidgets.QGridLayout()
        self.sim_grid.setContentsMargins(10, 10, 10, 10)
        self.sim_grid.setObjectName("sim_grid")
        self.sim_id_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.sim_id_input.setMaxLength(5)
        self.sim_id_input.setObjectName("sim_id_input")
        self.sim_grid.addWidget(self.sim_id_input, 0, 0, 1, 1)
        self.copy_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.copy_btn.setObjectName("copy_btn")
        self.sim_grid.addWidget(self.copy_btn, 0, 2, 1, 1)
        self.replay_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.replay_btn.setObjectName("replay_btn")
        self.sim_grid.addWidget(self.replay_btn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.sim_grid)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.opts_grid = QtWidgets.QGridLayout()
        self.opts_grid.setContentsMargins(10, 10, 10, 10)
        self.opts_grid.setObjectName("opts_grid")
        self.ant_size = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.ant_size.setObjectName("ant_size")
        self.opts_grid.addWidget(self.ant_size, 1, 0, 1, 1)
        self.offset_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.offset_spinbox.setProperty("value", 50)
        self.offset_spinbox.setObjectName("offset_spinbox")
        self.opts_grid.addWidget(self.offset_spinbox, 2, 1, 1, 1)
        self.food_radius_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.food_radius_spinbox.setProperty("value", 50)
        self.food_radius_spinbox.setObjectName("food_radius_spinbox")
        self.opts_grid.addWidget(self.food_radius_spinbox, 6, 3, 1, 1)
        self.domain_size = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.domain_size.setObjectName("domain_size")
        self.opts_grid.addWidget(self.domain_size, 1, 2, 1, 1)
        self.sens_activation = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.sens_activation.setObjectName("sens_activation")
        self.opts_grid.addWidget(self.sens_activation, 3, 0, 1, 1)
        self.nest_radius = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.nest_radius.setObjectName("nest_radius")
        self.opts_grid.addWidget(self.nest_radius, 4, 2, 1, 1)
        self.dep_dict_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.dep_dict_input.setObjectName("dep_dict_input")
        self.opts_grid.addWidget(self.dep_dict_input, 5, 1, 1, 1)
        self.pitch = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.pitch.setObjectName("pitch")
        self.opts_grid.addWidget(self.pitch, 2, 2, 1, 1)
        self.sens_offset = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.sens_offset.setObjectName("sens_offset")
        self.opts_grid.addWidget(self.sens_offset, 2, 0, 1, 1)
        self.dep_dict = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dep_dict.setObjectName("dep_dict")
        self.opts_grid.addWidget(self.dep_dict, 5, 0, 1, 1)
        self.run_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.run_button.setObjectName("run_button")
        self.opts_grid.addWidget(self.run_button, 0, 0, 1, 1)
        self.sens_activation_combox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.sens_activation_combox.setEditable(False)
        self.sens_activation_combox.setObjectName("sens_activation_combox")
        self.sens_activation_combox.addItem("")
        self.sens_activation_combox.addItem("")
        self.opts_grid.addWidget(self.sens_activation_combox, 3, 1, 1, 1)
        self.nest_radius_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.nest_radius_spinbox.setProperty("value", 50)
        self.nest_radius_spinbox.setObjectName("nest_radius_spinbox")
        self.opts_grid.addWidget(self.nest_radius_spinbox, 4, 3, 1, 1)
        self.food_location = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.food_location.setObjectName("food_location")
        self.opts_grid.addWidget(self.food_location, 5, 2, 1, 1)
        self.food_radius = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.food_radius.setObjectName("food_radius")
        self.opts_grid.addWidget(self.food_radius, 6, 2, 1, 1)
        self.nest_location = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.nest_location.setObjectName("nest_location")
        self.opts_grid.addWidget(self.nest_location, 3, 2, 1, 1)
        self.start_pheromone = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.start_pheromone.setObjectName("start_pheromone")
        self.opts_grid.addWidget(self.start_pheromone, 6, 0, 1, 1)
        self.deposit_fun_combox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.deposit_fun_combox.setObjectName("deposit_fun_combox")
        self.deposit_fun_combox.addItem("")
        self.deposit_fun_combox.addItem("")
        self.opts_grid.addWidget(self.deposit_fun_combox, 4, 1, 1, 1)
        self.dep_fun = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dep_fun.setObjectName("dep_fun")
        self.opts_grid.addWidget(self.dep_fun, 4, 0, 1, 1)
        self.antsize_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.antsize_spinbox.setProperty("value", 50)
        self.antsize_spinbox.setObjectName("antsize_spinbox")
        self.opts_grid.addWidget(self.antsize_spinbox, 1, 1, 1, 1)
        self.dom_box = QtWidgets.QHBoxLayout()
        self.dom_box.setObjectName("dom_box")
        self.dom_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.dom_x_size.setProperty("value", 50)
        self.dom_x_size.setObjectName("dom_x_size")
        self.dom_box.addWidget(self.dom_x_size)
        self.dom_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.dom_y_size.setProperty("value", 50)
        self.dom_y_size.setObjectName("dom_y_size")
        self.dom_box.addWidget(self.dom_y_size)
        self.opts_grid.addLayout(self.dom_box, 1, 3, 1, 1)
        self.nest_box = QtWidgets.QHBoxLayout()
        self.nest_box.setObjectName("nest_box")
        self.nest_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.nest_x_size.setProperty("value", 50)
        self.nest_x_size.setObjectName("nest_x_size")
        self.nest_box.addWidget(self.nest_x_size)
        self.nest_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.nest_y_size.setProperty("value", 50)
        self.nest_y_size.setObjectName("nest_y_size")
        self.nest_box.addWidget(self.nest_y_size)
        self.opts_grid.addLayout(self.nest_box, 3, 3, 1, 1)
        self.food_box = QtWidgets.QHBoxLayout()
        self.food_box.setObjectName("food_box")
        self.food_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.food_x_size.setMaximum(10000)
        self.food_x_size.setSingleStep(100)
        self.food_x_size.setProperty("value", 3500)
        self.food_x_size.setObjectName("food_x_size")
        self.food_box.addWidget(self.food_x_size)
        self.food_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.food_y_size.setMaximum(10000)
        self.food_y_size.setSingleStep(100)
        self.food_y_size.setProperty("value", 2000)
        self.food_y_size.setObjectName("food_y_size")
        self.food_box.addWidget(self.food_y_size)
        self.opts_grid.addLayout(self.food_box, 5, 3, 1, 1)
        self.pitch_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.pitch_spinbox.setProperty("value", 50)
        self.pitch_spinbox.setObjectName("pitch_spinbox")
        self.opts_grid.addWidget(self.pitch_spinbox, 2, 3, 1, 1)
        self.pheromone_spinbox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.pheromone_spinbox.setMinimum(-1.0)
        self.pheromone_spinbox.setSingleStep(0.25)
        self.pheromone_spinbox.setProperty("value", 1.0)
        self.pheromone_spinbox.setObjectName("pheromone_spinbox")
        self.opts_grid.addWidget(self.pheromone_spinbox, 6, 1, 1, 1)
        self.check_visualize = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.check_visualize.setObjectName("check_visualize")
        self.opts_grid.addWidget(self.check_visualize, 0, 2, 1, 1)
        self.check_recording = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.check_recording.setObjectName("check_recording")
        self.opts_grid.addWidget(self.check_recording, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.opts_grid)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 30))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textbox_status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">--placeholder--</p></body></html>"))
        self.sim_id_input.setText(_translate("MainWindow", "86"))
        self.sim_id_input.setPlaceholderText(_translate("MainWindow", "1"))
        self.copy_btn.setText(_translate("MainWindow", "Copy"))
        self.replay_btn.setText(_translate("MainWindow", "Replay"))
        self.ant_size.setText(_translate("MainWindow", "L (ant size)"))
        self.domain_size.setText(_translate("MainWindow", "Domain size"))
        self.sens_activation.setText(_translate("MainWindow", "sensor activation"))
        self.nest_radius.setText(_translate("MainWindow", "nest_radius"))
        self.dep_dict_input.setText(_translate("MainWindow", "{\'q\':1.,\'return_factor\':1.,\'beta\':0.05}"))
        self.pitch.setText(_translate("MainWindow", "pitch"))
        self.sens_offset.setText(_translate("MainWindow", "sensor offset"))
        self.dep_dict.setText(_translate("MainWindow", "Deposit dict"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.sens_activation_combox.setCurrentText(_translate("MainWindow", "linear"))
        self.sens_activation_combox.setItemText(0, _translate("MainWindow", "linear"))
        self.sens_activation_combox.setItemText(1, _translate("MainWindow", "sigmoid"))
        self.food_location.setText(_translate("MainWindow", "food_location"))
        self.food_radius.setText(_translate("MainWindow", "food_radius"))
        self.nest_location.setText(_translate("MainWindow", "nest location"))
        self.start_pheromone.setText(_translate("MainWindow", "Start pheromone level"))
        self.deposit_fun_combox.setCurrentText(_translate("MainWindow", "constant"))
        self.deposit_fun_combox.setItemText(0, _translate("MainWindow", "constant"))
        self.deposit_fun_combox.setItemText(1, _translate("MainWindow", "exponential"))
        self.dep_fun.setText(_translate("MainWindow", "deposit function"))
        self.check_visualize.setText(_translate("MainWindow", "Visualize"))
        self.check_recording.setText(_translate("MainWindow", "Recording"))
        self.menuMenu.setTitle(_translate("MainWindow", "&Menu"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

