# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/sim_launcher.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 971)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 661, 901))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textbox_status = QtWidgets.QTextBrowser(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textbox_status.sizePolicy().hasHeightForWidth())
        self.textbox_status.setSizePolicy(sizePolicy)
        self.textbox_status.setObjectName("textbox_status")
        self.verticalLayout.addWidget(self.textbox_status)
        self.sim_grid = QtWidgets.QGridLayout()
        self.sim_grid.setContentsMargins(10, 10, 10, 10)
        self.sim_grid.setObjectName("sim_grid")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.replay_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.replay_btn.setObjectName("replay_btn")
        self.horizontalLayout_6.addWidget(self.replay_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.sim_grid.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.button_run = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.button_run.setDefault(False)
        self.button_run.setFlat(False)
        self.button_run.setObjectName("button_run")
        self.horizontalLayout_18.addWidget(self.button_run)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.sim_grid.addLayout(self.horizontalLayout_18, 0, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sim_grid.addLayout(self.horizontalLayout_3, 1, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_nagents = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_nagents.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nagents.setObjectName("label_nagents")
        self.horizontalLayout_5.addWidget(self.label_nagents)
        self.spinbox_agents = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinbox_agents.setMinimum(1)
        self.spinbox_agents.setMaximum(999)
        self.spinbox_agents.setSingleStep(5)
        self.spinbox_agents.setProperty("value", 80)
        self.spinbox_agents.setObjectName("spinbox_agents")
        self.horizontalLayout_5.addWidget(self.spinbox_agents)
        self.sim_grid.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_interval = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_interval.setObjectName("label_interval")
        self.horizontalLayout_21.addWidget(self.label_interval)
        self.spinbox_interval = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinbox_interval.setMinimum(1)
        self.spinbox_interval.setMaximum(1000)
        self.spinbox_interval.setSingleStep(100)
        self.spinbox_interval.setProperty("value", 500)
        self.spinbox_interval.setObjectName("spinbox_interval")
        self.horizontalLayout_21.addWidget(self.spinbox_interval)
        self.sim_grid.addLayout(self.horizontalLayout_21, 2, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.copy_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.copy_btn.setObjectName("copy_btn")
        self.horizontalLayout_7.addWidget(self.copy_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.sim_grid.addLayout(self.horizontalLayout_7, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_dt = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_dt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dt.setObjectName("label_dt")
        self.horizontalLayout_4.addWidget(self.label_dt)
        self.spinbox_dt = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.spinbox_dt.setMinimum(0.01)
        self.spinbox_dt.setMaximum(10.0)
        self.spinbox_dt.setSingleStep(0.1)
        self.spinbox_dt.setProperty("value", 0.5)
        self.spinbox_dt.setObjectName("spinbox_dt")
        self.horizontalLayout_4.addWidget(self.spinbox_dt)
        self.sim_grid.addLayout(self.horizontalLayout_4, 1, 4, 1, 1)
        self.sim_id_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.sim_id_input.setMaxLength(5)
        self.sim_id_input.setObjectName("sim_id_input")
        self.sim_grid.addWidget(self.sim_id_input, 0, 0, 1, 1)
        self.check_visualize = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.check_visualize.setChecked(True)
        self.check_visualize.setObjectName("check_visualize")
        self.sim_grid.addWidget(self.check_visualize, 1, 1, 1, 1)
        self.check_recording = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.check_recording.setChecked(True)
        self.check_recording.setObjectName("check_recording")
        self.sim_grid.addWidget(self.check_recording, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_steps = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_steps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_steps.setObjectName("label_steps")
        self.horizontalLayout_8.addWidget(self.label_steps)
        self.spinbox_steps = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinbox_steps.setMinimum(1)
        self.spinbox_steps.setMaximum(99999)
        self.spinbox_steps.setSingleStep(500)
        self.spinbox_steps.setProperty("value", 1500)
        self.spinbox_steps.setObjectName("spinbox_steps")
        self.horizontalLayout_8.addWidget(self.spinbox_steps)
        self.sim_grid.addLayout(self.horizontalLayout_8, 2, 4, 1, 1)
        self.verticalLayout.addLayout(self.sim_grid)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 621, 483))
        self.layoutWidget.setObjectName("layoutWidget")
        self.opts_grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.opts_grid.setContentsMargins(10, 10, 10, 10)
        self.opts_grid.setObjectName("opts_grid")
        self.checkBox_override = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_override.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_override.setObjectName("checkBox_override")
        self.opts_grid.addWidget(self.checkBox_override, 13, 0, 1, 1)
        self.label_noisegain_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_noisegain_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_noisegain_2.setWordWrap(True)
        self.label_noisegain_2.setObjectName("label_noisegain_2")
        self.opts_grid.addWidget(self.label_noisegain_2, 10, 2, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.spinbox_noisegain_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_noisegain_2.setMaximum(10.0)
        self.spinbox_noisegain_2.setSingleStep(0.25)
        self.spinbox_noisegain_2.setProperty("value", 1.0)
        self.spinbox_noisegain_2.setObjectName("spinbox_noisegain_2")
        self.horizontalLayout_17.addWidget(self.spinbox_noisegain_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.opts_grid.addLayout(self.horizontalLayout_17, 10, 3, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.combobox_activation = QtWidgets.QComboBox(self.layoutWidget)
        self.combobox_activation.setEditable(False)
        self.combobox_activation.setObjectName("combobox_activation")
        self.combobox_activation.addItem("")
        self.combobox_activation.addItem("")
        self.horizontalLayout_26.addWidget(self.combobox_activation)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.opts_grid.addLayout(self.horizontalLayout_26, 7, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_antsize = QtWidgets.QLabel(self.layoutWidget)
        self.label_antsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_antsize.setObjectName("label_antsize")
        self.horizontalLayout_23.addWidget(self.label_antsize)
        self.opts_grid.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.spinbox_antdropper = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_antdropper.setProperty("value", 50)
        self.spinbox_antdropper.setObjectName("spinbox_antdropper")
        self.horizontalLayout_24.addWidget(self.spinbox_antdropper)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.opts_grid.addLayout(self.horizontalLayout_24, 2, 1, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.spinbox_speed = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_speed.setMaximum(999)
        self.spinbox_speed.setSingleStep(25)
        self.spinbox_speed.setProperty("value", 125)
        self.spinbox_speed.setObjectName("spinbox_speed")
        self.horizontalLayout_33.addWidget(self.spinbox_speed)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem7)
        self.opts_grid.addLayout(self.horizontalLayout_33, 2, 3, 1, 1)
        self.label_offset = QtWidgets.QLabel(self.layoutWidget)
        self.label_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_offset.setObjectName("label_offset")
        self.opts_grid.addWidget(self.label_offset, 1, 2, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.combobox_noise = QtWidgets.QComboBox(self.layoutWidget)
        self.combobox_noise.setObjectName("combobox_noise")
        self.combobox_noise.addItem("")
        self.combobox_noise.addItem("")
        self.combobox_noise.addItem("")
        self.horizontalLayout_28.addWidget(self.combobox_noise)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem8)
        self.opts_grid.addLayout(self.horizontalLayout_28, 9, 1, 1, 1)
        self.label_activation = QtWidgets.QLabel(self.layoutWidget)
        self.label_activation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_activation.setObjectName("label_activation")
        self.opts_grid.addWidget(self.label_activation, 7, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.spinbox_gain = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_gain.setMinimum(0.05)
        self.spinbox_gain.setMaximum(10.0)
        self.spinbox_gain.setSingleStep(0.25)
        self.spinbox_gain.setProperty("value", 1.5)
        self.spinbox_gain.setObjectName("spinbox_gain")
        self.horizontalLayout_20.addWidget(self.spinbox_gain)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.opts_grid.addLayout(self.horizontalLayout_20, 8, 3, 1, 1)
        self.label_gain = QtWidgets.QLabel(self.layoutWidget)
        self.label_gain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_gain.setObjectName("label_gain")
        self.opts_grid.addWidget(self.label_gain, 8, 2, 1, 1)
        self.label_breakpoint = QtWidgets.QLabel(self.layoutWidget)
        self.label_breakpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_breakpoint.setObjectName("label_breakpoint")
        self.opts_grid.addWidget(self.label_breakpoint, 7, 2, 1, 1)
        self.label_rotate_fun = QtWidgets.QLabel(self.layoutWidget)
        self.label_rotate_fun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rotate_fun.setWordWrap(True)
        self.label_rotate_fun.setObjectName("label_rotate_fun")
        self.opts_grid.addWidget(self.label_rotate_fun, 8, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.opts_grid.addItem(spacerItem10, 17, 1, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.spinbox_breakpoint = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_breakpoint.setMinimum(-1.0)
        self.spinbox_breakpoint.setSingleStep(0.25)
        self.spinbox_breakpoint.setProperty("value", 1.0)
        self.spinbox_breakpoint.setObjectName("spinbox_breakpoint")
        self.horizontalLayout_34.addWidget(self.spinbox_breakpoint)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem11)
        self.opts_grid.addLayout(self.horizontalLayout_34, 7, 3, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.spinbox_regularization = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_regularization.setDecimals(4)
        self.spinbox_regularization.setMinimum(0.0)
        self.spinbox_regularization.setSingleStep(0.001)
        self.spinbox_regularization.setProperty("value", 0.005)
        self.spinbox_regularization.setObjectName("spinbox_regularization")
        self.horizontalLayout_31.addWidget(self.spinbox_regularization)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.opts_grid.addLayout(self.horizontalLayout_31, 9, 3, 1, 1)
        self.label_speed = QtWidgets.QLabel(self.layoutWidget)
        self.label_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_speed.setObjectName("label_speed")
        self.opts_grid.addWidget(self.label_speed, 2, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.opts_grid.addWidget(self.line_6, 12, 0, 1, 4)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.opts_grid.addWidget(self.line_7, 14, 0, 1, 4)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.spinbox_offset = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_offset.setMinimum(10)
        self.spinbox_offset.setMaximum(90)
        self.spinbox_offset.setSingleStep(5)
        self.spinbox_offset.setProperty("value", 45)
        self.spinbox_offset.setDisplayIntegerBase(10)
        self.spinbox_offset.setObjectName("spinbox_offset")
        self.horizontalLayout_32.addWidget(self.spinbox_offset)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem13)
        self.opts_grid.addLayout(self.horizontalLayout_32, 1, 3, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.spinbox_antsize = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_antsize.setProperty("value", 50)
        self.spinbox_antsize.setObjectName("spinbox_antsize")
        self.horizontalLayout_25.addWidget(self.spinbox_antsize)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem14)
        self.opts_grid.addLayout(self.horizontalLayout_25, 1, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_antdropper = QtWidgets.QLabel(self.layoutWidget)
        self.label_antdropper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_antdropper.setObjectName("label_antdropper")
        self.horizontalLayout_22.addWidget(self.label_antdropper)
        self.opts_grid.addLayout(self.horizontalLayout_22, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.opts_grid.addWidget(self.line_2, 4, 0, 1, 4)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.combobox_rotate = QtWidgets.QComboBox(self.layoutWidget)
        self.combobox_rotate.setEditable(False)
        self.combobox_rotate.setObjectName("combobox_rotate")
        self.combobox_rotate.addItem("")
        self.combobox_rotate.addItem("")
        self.horizontalLayout_27.addWidget(self.combobox_rotate)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem15)
        self.opts_grid.addLayout(self.horizontalLayout_27, 8, 1, 1, 1)
        self.label_regularization = QtWidgets.QLabel(self.layoutWidget)
        self.label_regularization.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_regularization.setObjectName("label_regularization")
        self.opts_grid.addWidget(self.label_regularization, 9, 2, 1, 1)
        self.label_noise = QtWidgets.QLabel(self.layoutWidget)
        self.label_noise.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_noise.setObjectName("label_noise")
        self.opts_grid.addWidget(self.label_noise, 9, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.spinbox_noisegain = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_noisegain.setMaximum(10.0)
        self.spinbox_noisegain.setSingleStep(0.25)
        self.spinbox_noisegain.setProperty("value", 1.0)
        self.spinbox_noisegain.setObjectName("spinbox_noisegain")
        self.horizontalLayout_19.addWidget(self.spinbox_noisegain)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem16)
        self.opts_grid.addLayout(self.horizontalLayout_19, 10, 1, 1, 1)
        self.label_noisegain = QtWidgets.QLabel(self.layoutWidget)
        self.label_noisegain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_noisegain.setWordWrap(True)
        self.label_noisegain.setObjectName("label_noisegain")
        self.opts_grid.addWidget(self.label_noisegain, 10, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.opts_grid.addItem(spacerItem17, 16, 2, 1, 1)
        self.label_noiseparameter = QtWidgets.QLabel(self.layoutWidget)
        self.label_noiseparameter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_noiseparameter.setObjectName("label_noiseparameter")
        self.opts_grid.addWidget(self.label_noiseparameter, 11, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.line_noiseparameter = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_noiseparameter.setMaxLength(5)
        self.line_noiseparameter.setClearButtonEnabled(True)
        self.line_noiseparameter.setObjectName("line_noiseparameter")
        self.horizontalLayout_29.addWidget(self.line_noiseparameter)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem18)
        self.opts_grid.addLayout(self.horizontalLayout_29, 11, 1, 1, 1)
        self.label_lambda = QtWidgets.QLabel(self.layoutWidget)
        self.label_lambda.setEnabled(False)
        self.label_lambda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lambda.setObjectName("label_lambda")
        self.opts_grid.addWidget(self.label_lambda, 11, 2, 1, 1)
        self.spinbox_lambda = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_lambda.setEnabled(False)
        self.spinbox_lambda.setMinimum(-1.0)
        self.spinbox_lambda.setSingleStep(0.25)
        self.spinbox_lambda.setProperty("value", 1.0)
        self.spinbox_lambda.setObjectName("spinbox_lambda")
        self.opts_grid.addWidget(self.spinbox_lambda, 11, 3, 1, 1)
        self.labe_antsettings = QtWidgets.QLabel(self.layoutWidget)
        self.labe_antsettings.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labe_antsettings.setObjectName("labe_antsettings")
        self.opts_grid.addWidget(self.labe_antsettings, 0, 0, 1, 1)
        self.labe_antsettings_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labe_antsettings_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labe_antsettings_2.setObjectName("labe_antsettings_2")
        self.opts_grid.addWidget(self.labe_antsettings_2, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinbox_override_max = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_override_max.setDecimals(1)
        self.spinbox_override_max.setMinimum(0.0)
        self.spinbox_override_max.setMaximum(1.0)
        self.spinbox_override_max.setSingleStep(0.1)
        self.spinbox_override_max.setProperty("value", 0.5)
        self.spinbox_override_max.setObjectName("spinbox_override_max")
        self.horizontalLayout_2.addWidget(self.spinbox_override_max)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.opts_grid.addLayout(self.horizontalLayout_2, 15, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinbox_override_time = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinbox_override_time.setDecimals(1)
        self.spinbox_override_time.setMinimum(0.0)
        self.spinbox_override_time.setMaximum(9999.0)
        self.spinbox_override_time.setSingleStep(1.0)
        self.spinbox_override_time.setProperty("value", 5.0)
        self.spinbox_override_time.setObjectName("spinbox_override_time")
        self.horizontalLayout.addWidget(self.spinbox_override_time)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.opts_grid.addLayout(self.horizontalLayout, 15, 3, 1, 1)
        self.label_override_max_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_override_max_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_override_max_2.setObjectName("label_override_max_2")
        self.opts_grid.addWidget(self.label_override_max_2, 15, 2, 1, 1)
        self.label_override_max = QtWidgets.QLabel(self.layoutWidget)
        self.label_override_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_override_max.setObjectName("label_override_max")
        self.opts_grid.addWidget(self.label_override_max, 15, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 541, 301))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_domainsize = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_domainsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_domainsize.setObjectName("label_domainsize")
        self.gridLayout_4.addWidget(self.label_domainsize, 0, 0, 1, 1)
        self.food_location = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.food_location.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.food_location.setObjectName("food_location")
        self.gridLayout_4.addWidget(self.food_location, 2, 0, 1, 1)
        self.food_box = QtWidgets.QHBoxLayout()
        self.food_box.setObjectName("food_box")
        self.food_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.food_x_size.setMinimum(0)
        self.food_x_size.setMaximum(10000)
        self.food_x_size.setSingleStep(250)
        self.food_x_size.setProperty("value", 3500)
        self.food_x_size.setObjectName("food_x_size")
        self.food_box.addWidget(self.food_x_size)
        self.food_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.food_y_size.setMinimum(0)
        self.food_y_size.setMaximum(10000)
        self.food_y_size.setSingleStep(250)
        self.food_y_size.setProperty("value", 2000)
        self.food_y_size.setObjectName("food_y_size")
        self.food_box.addWidget(self.food_y_size)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.food_box.addItem(spacerItem21)
        self.gridLayout_4.addLayout(self.food_box, 2, 1, 1, 1)
        self.label_pitch = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_pitch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pitch.setObjectName("label_pitch")
        self.gridLayout_4.addWidget(self.label_pitch, 3, 0, 1, 1)
        self.spinbox_foodradius = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinbox_foodradius.setMinimum(25)
        self.spinbox_foodradius.setMaximum(999)
        self.spinbox_foodradius.setSingleStep(50)
        self.spinbox_foodradius.setProperty("value", 150)
        self.spinbox_foodradius.setObjectName("spinbox_foodradius")
        self.gridLayout_4.addWidget(self.spinbox_foodradius, 2, 3, 1, 1)
        self.spinbox_nestradius = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinbox_nestradius.setMinimum(25)
        self.spinbox_nestradius.setMaximum(999)
        self.spinbox_nestradius.setSingleStep(50)
        self.spinbox_nestradius.setProperty("value", 150)
        self.spinbox_nestradius.setObjectName("spinbox_nestradius")
        self.gridLayout_4.addWidget(self.spinbox_nestradius, 1, 3, 1, 1)
        self.label_nestradius = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_nestradius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nestradius.setObjectName("label_nestradius")
        self.gridLayout_4.addWidget(self.label_nestradius, 1, 2, 1, 1)
        self.label_foodradius = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_foodradius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_foodradius.setObjectName("label_foodradius")
        self.gridLayout_4.addWidget(self.label_foodradius, 2, 2, 1, 1)
        self.nest_box = QtWidgets.QHBoxLayout()
        self.nest_box.setObjectName("nest_box")
        self.nest_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.nest_x_size.setMinimum(0)
        self.nest_x_size.setMaximum(10000)
        self.nest_x_size.setSingleStep(250)
        self.nest_x_size.setProperty("value", 500)
        self.nest_x_size.setObjectName("nest_x_size")
        self.nest_box.addWidget(self.nest_x_size)
        self.nest_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.nest_y_size.setMinimum(0)
        self.nest_y_size.setMaximum(10000)
        self.nest_y_size.setSingleStep(250)
        self.nest_y_size.setProperty("value", 3500)
        self.nest_y_size.setObjectName("nest_y_size")
        self.nest_box.addWidget(self.nest_y_size)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nest_box.addItem(spacerItem22)
        self.gridLayout_4.addLayout(self.nest_box, 1, 1, 1, 1)
        self.dom_box = QtWidgets.QHBoxLayout()
        self.dom_box.setObjectName("dom_box")
        self.dom_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.dom_x_size.setMinimum(500)
        self.dom_x_size.setMaximum(10000)
        self.dom_x_size.setSingleStep(500)
        self.dom_x_size.setProperty("value", 4000)
        self.dom_x_size.setObjectName("dom_x_size")
        self.dom_box.addWidget(self.dom_x_size)
        self.dom_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.dom_y_size.setMinimum(500)
        self.dom_y_size.setMaximum(10000)
        self.dom_y_size.setSingleStep(500)
        self.dom_y_size.setProperty("value", 4000)
        self.dom_y_size.setObjectName("dom_y_size")
        self.dom_box.addWidget(self.dom_y_size)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dom_box.addItem(spacerItem23)
        self.gridLayout_4.addLayout(self.dom_box, 0, 1, 1, 1)
        self.label_nestlocation = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_nestlocation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nestlocation.setObjectName("label_nestlocation")
        self.gridLayout_4.addWidget(self.label_nestlocation, 1, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem24, 4, 1, 1, 1)
        self.label_startpheromone = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_startpheromone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_startpheromone.setObjectName("label_startpheromone")
        self.gridLayout_4.addWidget(self.label_startpheromone, 0, 2, 1, 1)
        self.spinbox_pheromone = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.spinbox_pheromone.setMinimum(-1.0)
        self.spinbox_pheromone.setSingleStep(0.25)
        self.spinbox_pheromone.setProperty("value", 1.0)
        self.spinbox_pheromone.setObjectName("spinbox_pheromone")
        self.gridLayout_4.addWidget(self.spinbox_pheromone, 0, 3, 1, 1)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.spinbox_pitch = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinbox_pitch.setMinimum(2)
        self.spinbox_pitch.setProperty("value", 10)
        self.spinbox_pitch.setObjectName("spinbox_pitch")
        self.horizontalLayout_35.addWidget(self.spinbox_pitch)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem25)
        self.gridLayout_4.addLayout(self.horizontalLayout_35, 3, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_evaporation = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_evaporation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_evaporation.setObjectName("label_evaporation")
        self.horizontalLayout_12.addWidget(self.label_evaporation)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 3, 2, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.spinbox_evaporation = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.spinbox_evaporation.setDecimals(3)
        self.spinbox_evaporation.setMinimum(-1.0)
        self.spinbox_evaporation.setMaximum(1.0)
        self.spinbox_evaporation.setSingleStep(0.1)
        self.spinbox_evaporation.setProperty("value", 0.98)
        self.spinbox_evaporation.setObjectName("spinbox_evaporation")
        self.horizontalLayout_36.addWidget(self.spinbox_evaporation)
        self.gridLayout_4.addLayout(self.horizontalLayout_36, 3, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem26, 4, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem27, 4, 3, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem28, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.combobox_depfun = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combobox_depfun.setObjectName("combobox_depfun")
        self.combobox_depfun.addItem("")
        self.combobox_depfun.addItem("")
        self.horizontalLayout_38.addWidget(self.combobox_depfun)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem29)
        self.gridLayout.addLayout(self.horizontalLayout_38, 4, 4, 1, 1)
        self.label_actuatorthings = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_actuatorthings.sizePolicy().hasHeightForWidth())
        self.label_actuatorthings.setSizePolicy(sizePolicy)
        self.label_actuatorthings.setObjectName("label_actuatorthings")
        self.gridLayout.addWidget(self.label_actuatorthings, 0, 0, 1, 1)
        self.label_depositbeta = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_depositbeta.sizePolicy().hasHeightForWidth())
        self.label_depositbeta.setSizePolicy(sizePolicy)
        self.label_depositbeta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_depositbeta.setObjectName("label_depositbeta")
        self.gridLayout.addWidget(self.label_depositbeta, 5, 3, 1, 1)
        self.label_covariance = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_covariance.sizePolicy().hasHeightForWidth())
        self.label_covariance.setSizePolicy(sizePolicy)
        self.label_covariance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_covariance.setObjectName("label_covariance")
        self.gridLayout.addWidget(self.label_covariance, 3, 0, 1, 1)
        self.label_dropquantity = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dropquantity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dropquantity.setObjectName("label_dropquantity")
        self.gridLayout.addWidget(self.label_dropquantity, 3, 3, 1, 1)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.spinbox_covariance = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinbox_covariance.setMaximum(999)
        self.spinbox_covariance.setSingleStep(5)
        self.spinbox_covariance.setProperty("value", 200)
        self.spinbox_covariance.setObjectName("spinbox_covariance")
        self.horizontalLayout_41.addWidget(self.spinbox_covariance)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem30)
        self.gridLayout.addLayout(self.horizontalLayout_41, 3, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 3, 1, 1)
        self.label_returnfactor = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_returnfactor.sizePolicy().hasHeightForWidth())
        self.label_returnfactor.setSizePolicy(sizePolicy)
        self.label_returnfactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_returnfactor.setObjectName("label_returnfactor")
        self.gridLayout.addWidget(self.label_returnfactor, 4, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 0, 4, 1, 1)
        self.label_depfun = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_depfun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_depfun.setObjectName("label_depfun")
        self.gridLayout.addWidget(self.label_depfun, 4, 3, 1, 1)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.spinbox_depositbeta = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinbox_depositbeta.setDecimals(3)
        self.spinbox_depositbeta.setMinimum(0.0)
        self.spinbox_depositbeta.setMaximum(1.0)
        self.spinbox_depositbeta.setSingleStep(0.025)
        self.spinbox_depositbeta.setProperty("value", 0.05)
        self.spinbox_depositbeta.setObjectName("spinbox_depositbeta")
        self.horizontalLayout_37.addWidget(self.spinbox_depositbeta)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem33)
        self.gridLayout.addLayout(self.horizontalLayout_37, 5, 4, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.spinbox_q = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_q.sizePolicy().hasHeightForWidth())
        self.spinbox_q.setSizePolicy(sizePolicy)
        self.spinbox_q.setDecimals(2)
        self.spinbox_q.setMinimum(0.01)
        self.spinbox_q.setMaximum(100.0)
        self.spinbox_q.setSingleStep(0.5)
        self.spinbox_q.setProperty("value", 0.5)
        self.spinbox_q.setObjectName("spinbox_q")
        self.horizontalLayout_30.addWidget(self.spinbox_q)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem34)
        self.gridLayout.addLayout(self.horizontalLayout_30, 3, 4, 1, 1)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.spinbox_significancy = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinbox_significancy.setMinimum(1)
        self.spinbox_significancy.setMaximum(5)
        self.spinbox_significancy.setSingleStep(1)
        self.spinbox_significancy.setProperty("value", 2)
        self.spinbox_significancy.setObjectName("spinbox_significancy")
        self.horizontalLayout_39.addWidget(self.spinbox_significancy)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem35)
        self.gridLayout.addLayout(self.horizontalLayout_39, 5, 1, 1, 1)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.spinbox_returnfactor = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinbox_returnfactor.setMinimum(0.0)
        self.spinbox_returnfactor.setMaximum(10.0)
        self.spinbox_returnfactor.setSingleStep(0.1)
        self.spinbox_returnfactor.setProperty("value", 1.0)
        self.spinbox_returnfactor.setObjectName("spinbox_returnfactor")
        self.horizontalLayout_40.addWidget(self.spinbox_returnfactor)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem36)
        self.gridLayout.addLayout(self.horizontalLayout_40, 4, 1, 1, 1)
        self.label_significancy = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_significancy.sizePolicy().hasHeightForWidth())
        self.label_significancy.setSizePolicy(sizePolicy)
        self.label_significancy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_significancy.setObjectName("label_significancy")
        self.gridLayout.addWidget(self.label_significancy, 5, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem37, 0, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem38, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 541, 166))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_deploy_tmax = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_deploy_tmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_deploy_tmax.setObjectName("label_deploy_tmax")
        self.horizontalLayout_16.addWidget(self.label_deploy_tmax)
        self.spinbox_deploytmax = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinbox_deploytmax.setMinimum(1)
        self.spinbox_deploytmax.setMaximum(999)
        self.spinbox_deploytmax.setSingleStep(5)
        self.spinbox_deploytmax.setProperty("value", 10)
        self.spinbox_deploytmax.setObjectName("spinbox_deploytmax")
        self.horizontalLayout_16.addWidget(self.spinbox_deploytmax)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem39)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 5, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 3, 1, 1, 3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_deploytiming = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_deploytiming.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_deploytiming.setObjectName("label_deploytiming")
        self.horizontalLayout_10.addWidget(self.label_deploytiming)
        self.combobox_timing = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_timing.sizePolicy().hasHeightForWidth())
        self.combobox_timing.setSizePolicy(sizePolicy)
        self.combobox_timing.setObjectName("combobox_timing")
        self.combobox_timing.addItem("")
        self.combobox_timing.addItem("")
        self.combobox_timing.addItem("")
        self.horizontalLayout_10.addWidget(self.combobox_timing)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem40)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 2, 2, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_deployarguments = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_deployarguments.setObjectName("label_deployarguments")
        self.horizontalLayout_13.addWidget(self.label_deployarguments)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 4, 1, 1, 3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_deploy_theta = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_deploy_theta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_deploy_theta.setObjectName("label_deploy_theta")
        self.horizontalLayout_15.addWidget(self.label_deploy_theta)
        self.spinbox_deploytheta = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spinbox_deploytheta.setProperty("value", 2.0)
        self.spinbox_deploytheta.setObjectName("spinbox_deploytheta")
        self.horizontalLayout_15.addWidget(self.spinbox_deploytheta)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem41)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 5, 2, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 2, 3, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_deploystyle = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_deploystyle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_deploystyle.setObjectName("label_deploystyle")
        self.horizontalLayout_9.addWidget(self.label_deploystyle)
        self.combobox_deployment = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_deployment.sizePolicy().hasHeightForWidth())
        self.combobox_deployment.setSizePolicy(sizePolicy)
        self.combobox_deployment.setObjectName("combobox_deployment")
        self.combobox_deployment.addItem("")
        self.horizontalLayout_9.addWidget(self.combobox_deployment)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem42)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.label_deploythings = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_deploythings.sizePolicy().hasHeightForWidth())
        self.label_deploythings.setSizePolicy(sizePolicy)
        self.label_deploythings.setObjectName("label_deploythings")
        self.gridLayout_2.addWidget(self.label_deploythings, 0, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_deploy_k = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_deploy_k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_deploy_k.setObjectName("label_deploy_k")
        self.horizontalLayout_14.addWidget(self.label_deploy_k)
        self.spinbox_deployk = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spinbox_deployk.setProperty("value", 10.0)
        self.spinbox_deployk.setObjectName("spinbox_deployk")
        self.horizontalLayout_14.addWidget(self.spinbox_deployk)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem43)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 5, 1, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem44, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 30))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.combobox_noise.setCurrentIndex(2)
        self.combobox_depfun.setCurrentIndex(0)
        self.combobox_timing.setCurrentIndex(0)
        self.combobox_deployment.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textbox_status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.replay_btn.setText(_translate("MainWindow", "Replay"))
        self.button_run.setText(_translate("MainWindow", "Run"))
        self.label_nagents.setText(_translate("MainWindow", "Colony size"))
        self.label_interval.setText(_translate("MainWindow", "DB write\n"
" interval"))
        self.copy_btn.setText(_translate("MainWindow", "Copy"))
        self.label_dt.setText(_translate("MainWindow", "dt:"))
        self.sim_id_input.setText(_translate("MainWindow", "4872"))
        self.sim_id_input.setPlaceholderText(_translate("MainWindow", "1"))
        self.check_visualize.setText(_translate("MainWindow", "Visualize"))
        self.check_recording.setText(_translate("MainWindow", "Recording"))
        self.label_steps.setText(_translate("MainWindow", "steps:"))
        self.checkBox_override.setText(_translate("MainWindow", "Control override"))
        self.label_noisegain_2.setText(_translate("MainWindow", "noise gain/cov #2:"))
        self.combobox_activation.setCurrentText(_translate("MainWindow", "linear"))
        self.combobox_activation.setItemText(0, _translate("MainWindow", "linear"))
        self.combobox_activation.setItemText(1, _translate("MainWindow", "ReLu"))
        self.label_antsize.setText(_translate("MainWindow", "L (antenna)[mm]:"))
        self.label_offset.setText(_translate("MainWindow", "sensor offset [deg]:"))
        self.combobox_noise.setCurrentText(_translate("MainWindow", "telegraph"))
        self.combobox_noise.setItemText(0, _translate("MainWindow", "white"))
        self.combobox_noise.setItemText(1, _translate("MainWindow", "uniform"))
        self.combobox_noise.setItemText(2, _translate("MainWindow", "telegraph"))
        self.label_activation.setText(_translate("MainWindow", "sensor activation:"))
        self.spinbox_gain.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ant steering gain K: d<span style=\" vertical-align:sub;\">theta</span>/d<span style=\" vertical-align:sub;\">t</span>=K*(Left-Right+noise)</p></body></html>"))
        self.label_gain.setText(_translate("MainWindow", "gain:"))
        self.label_breakpoint.setText(_translate("MainWindow", "breakpoint (ReLu):"))
        self.label_rotate_fun.setText(_translate("MainWindow", "Control function"))
        self.label_speed.setText(_translate("MainWindow", "speed [mm/s]:"))
        self.label_antdropper.setText(_translate("MainWindow", "d (actuator) [mm]:"))
        self.combobox_rotate.setCurrentText(_translate("MainWindow", "simple"))
        self.combobox_rotate.setItemText(0, _translate("MainWindow", "simple"))
        self.combobox_rotate.setItemText(1, _translate("MainWindow", "weber"))
        self.label_regularization.setText(_translate("MainWindow", "k (weber reg.)"))
        self.label_noise.setText(_translate("MainWindow", "noise type (sensor):"))
        self.label_noisegain.setText(_translate("MainWindow", "noise gain/cov #1:"))
        self.label_noiseparameter.setText(_translate("MainWindow", "noise parameter\n"
"(telegraph):"))
        self.line_noiseparameter.setText(_translate("MainWindow", "0.5"))
        self.label_lambda.setText(_translate("MainWindow", "lambda (sigmoid):"))
        self.labe_antsettings.setText(_translate("MainWindow", "Agent properties"))
        self.labe_antsettings_2.setText(_translate("MainWindow", "Control properties"))
        self.label_override_max_2.setText(_translate("MainWindow", "Override time [s]"))
        self.label_override_max.setText(_translate("MainWindow", "Override factor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ant settings"))
        self.label_domainsize.setText(_translate("MainWindow", "domain size:"))
        self.food_location.setText(_translate("MainWindow", "food_location:"))
        self.label_pitch.setText(_translate("MainWindow", "pitch:"))
        self.label_nestradius.setText(_translate("MainWindow", "nest_radius:"))
        self.label_foodradius.setText(_translate("MainWindow", "food_radius:"))
        self.label_nestlocation.setText(_translate("MainWindow", "nest location:"))
        self.label_startpheromone.setText(_translate("MainWindow", "start pheromone level:"))
        self.label_evaporation.setText(_translate("MainWindow", "evap_rate:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Domain settings"))
        self.combobox_depfun.setCurrentText(_translate("MainWindow", "constant"))
        self.combobox_depfun.setItemText(0, _translate("MainWindow", "constant"))
        self.combobox_depfun.setItemText(1, _translate("MainWindow", "exponential"))
        self.label_actuatorthings.setText(_translate("MainWindow", "Actuator settings"))
        self.label_depositbeta.setText(_translate("MainWindow", "Deposit decay parameter\n"
" (beta):"))
        self.label_covariance.setText(_translate("MainWindow", "Deposit covariance:"))
        self.label_dropquantity.setText(_translate("MainWindow", "Q (deposit \n"
" quantity):"))
        self.label_returnfactor.setText(_translate("MainWindow", "Return factor"))
        self.label_depfun.setText(_translate("MainWindow", "deposit function:"))
        self.label_significancy.setText(_translate("MainWindow", "Gaussian \n"
"significant digits: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pheromone depositon settings"))
        self.label_deploy_tmax.setText(_translate("MainWindow", "t_max (timing \n"
" uniform dist):"))
        self.label_deploytiming.setText(_translate("MainWindow", "timing:"))
        self.combobox_timing.setCurrentText(_translate("MainWindow", "instant"))
        self.combobox_timing.setItemText(0, _translate("MainWindow", "instant"))
        self.combobox_timing.setItemText(1, _translate("MainWindow", "gamma_dist"))
        self.combobox_timing.setItemText(2, _translate("MainWindow", "uniform_dist"))
        self.label_deployarguments.setText(_translate("MainWindow", "deploy timing arguments:"))
        self.label_deploy_theta.setText(_translate("MainWindow", "teta (timing \n"
" gamma dist):"))
        self.label_deploystyle.setText(_translate("MainWindow", "deployment:"))
        self.combobox_deployment.setCurrentText(_translate("MainWindow", "nest_radian"))
        self.combobox_deployment.setItemText(0, _translate("MainWindow", "nest_radian"))
        self.label_deploythings.setText(_translate("MainWindow", "Deploy specific settings"))
        self.label_deploy_k.setText(_translate("MainWindow", "k (timing \n"
" gamma dist):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Deployment settings"))
        self.menuMenu.setTitle(_translate("MainWindow", "&Menu"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))


